Repository InfinyTech3D/CollisionAlgorithm, pull requests merged in 2025-08, with the labels that each got.

#49 [algorithm] Refactor PR #3 - Add sanity checks and failproof
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: enhancement, pr: status to review

#50 [algorithm] Refactor PR #4 - Proper iterator use
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: clean, pr: status ready

#51 [algorithm] Refactor PR #5 - Remove needlePts variable
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: clean, pr: enhancement, pr: status ready

#52 [algorithm] Refactor PR #6 - Rework order of removal/addition of coupling points
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: enhancement, pr: fix, pr: status ready

#54 [algorithm] Enable collision between the needle (body) and the surface
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: new feature, pr: status to review

#58 [scene] Fix force feedback for haptics and insertion - addition of 2 scenes
  scenes/InsertionHaptics_Box.py
  scenes/InsertionHaptics_Liver.py
Labels: pr: fix, pr: status to review

#66 [ci] Add github ci workflow to compile plugin using SOFA master
  .github/workflows/ci.yml
  .github/workflows/delete-workflow-runs.yml
  CMakeLists.txt
  src/sofa/collisionAlgorithm/algorithm/InsertionAlgorithm.h
Labels: pr: enhancement, pr: status ready
